
CREATE TABLE IF NOT EXISTS CITY (ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255), STATE VARCHAR(255), COUNTRY VARCHAR(255));

INSERT INTO CITY (NAME, STATE, COUNTRY) VALUES ('beijin', 'CA', 'China');
